name: CI Pipeline - MLProject to Docker Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mlflow-ci-advanced:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil seluruh kode dari repositori GitHub
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Siapkan lingkungan Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # 3. Install seluruh library yang dibutuhkan 
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn mlflow dagshub matplotlib seaborn

    # 4. Jalankan pelatihan model secara lokal di server CI
    - name: Run MLflow Project
      run: |
        export MLFLOW_TRACKING_URI=file:./mlruns
        cd MLProject
        python -u modelling.py

    # 5. Otentikasi masuk ke akun Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 6. Bangun Docker Image menggunakan Dockerfile standar industri
    - name: Build Docker Image via Dockerfile
      run: |
        docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/credit-risk-model:latest" ./MLProject

    # 7. Unggah Docker Image yang sudah jadi ke Docker Hub Cloud
    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/credit-risk-model:latest

    # 8. Gunakan GitHub Artifacts
    - name: Upload Model Artifact to GitHub Web
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/model/
