name: CI Pipeline - MLProject to Docker Hub

# Terpantik otomatis setiap ada push ke branch main
on:
  push:
    branches:
      - main
  workflow_dispatch: # Memungkinkan tombol jalankan manual di GitHub Actions

permissions:
  contents: write

jobs:
  mlflow-ci-advanced:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    # 1. Ambil seluruh kode dari repositori GitHub
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Siapkan lingkungan Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # 3. Install seluruh library
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn mlflow dagshub matplotlib seaborn

    # 4. Jalankan MLProject secara otomatis di server GitHub
    - name: Run MLflow Project
      run: |
        mlflow run MLProject --env-manager=local

    # 5. Login ke akun Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 6. Bangun Docker Image
    - name: Build Docker Image via MLflow Function
      run: |
        mlflow models build-docker -m "MLProject/model" -n "${{ secrets.DOCKERHUB_USERNAME }}/credit-risk-model:latest" --env-manager=local

    # 7. Unggah (Push) Docker Image yang sudah jadi ke Docker Hub Cloud
    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/credit-risk-model:latest

    # 8. Simpan berkas model (Artefak) ke repositori GitHub saat ini
    - name: Commit and Push Local Artifacts
      run: |
        git config --local user.email "github-actions[bot]@://github.com"
        git config --local user.name "github-actions[bot]"
        
        git add MLProject/model/
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Automated CI: Update local model artifact [skip ci]"
          git push
        else
          echo "Tidak ada perubahan artefak yang perlu disimpan."
        fi
